services:
  - type: web
    name: codechef-scraper-api
    env: node
    plan: free
    branch: main
    buildCommand: |
      # Install dependencies
      apt-get update && apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgbm1 \
        libgcc1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        lsb-release \
        wget \
        xdg-utils \
        --no-install-recommends
      
      # Install Node dependencies
      npm ci

      echo "Installing puppeteer from render yaml"
      
      # Create a persistent directory for Chrome
      mkdir -p /opt/render/project/src/chrome
      chmod -R 777 /opt/render/project/src/chrome
      
      # Set environment variables for Chrome installation
      export PUPPETEER_DOWNLOAD_BASE_URL=https://storage.googleapis.com/chrome-for-testing-public
      export PUPPETEER_CACHE_DIR=/opt/render/project/src/chrome
      
      # Install Chrome
      echo "Installing Chrome..."
      npx puppeteer browsers install chrome@136.0.7103.92
      
      # Verify installation
      echo "Verifying Chrome installation..."
      CHROME_PATH="/opt/render/project/src/chrome/chrome/linux-136.0.7103.92/chrome-linux64/chrome"
      if [ -f "$CHROME_PATH" ]; then
        echo "Chrome found at: $CHROME_PATH"
        ls -la "$CHROME_PATH"
      else
        echo "Chrome not found at expected path!"
        echo "Searching for Chrome binary..."
        find /opt/render/project/src/chrome -type f -name "chrome" | xargs ls -la
      fi
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: '/opt/render/project/src/chrome'
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: 'false'
      - key: PUPPETEER_DOWNLOAD_BASE_URL
        value: 'https://storage.googleapis.com/chrome-for-testing-public'
      - key: PUPPETEER_EXECUTABLE_PATH
        value: '/opt/render/project/src/chrome/chrome/linux-136.0.7103.92/chrome-linux64/chrome'
    healthCheckPath: /health