services:
  - type: web
    name: codechef-scraper-api
    env: node
    plan: free
    branch: main
    buildCommand: |
      # Install Chrome dependencies
      apt-get update && apt-get install -y \
        ca-certificates \
        fonts-liberation \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libc6 \
        libcairo2 \
        libcups2 \
        libdbus-1-3 \
        libexpat1 \
        libfontconfig1 \
        libgbm1 \
        libgcc1 \
        libglib2.0-0 \
        libgtk-3-0 \
        libnspr4 \
        libnss3 \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libstdc++6 \
        libx11-6 \
        libx11-xcb1 \
        libxcb1 \
        libxcomposite1 \
        libxcursor1 \
        libxdamage1 \
        libxext6 \
        libxfixes3 \
        libxi6 \
        libxrandr2 \
        libxrender1 \
        libxss1 \
        libxtst6 \
        lsb-release \
        wget \
        xdg-utils \
        --no-install-recommends
      
      # Install Node dependencies
      npm ci
      
      # Create cache directory with proper permissions
      mkdir -p /opt/render/.cache/puppeteer
      chmod -R 777 /opt/render/.cache/puppeteer
      
      # Install Chrome through Puppeteer
      echo "Installing Chrome browser..."
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=false npm run install-browsers
      
      # Verify Chrome installation
      CHROME_PATH=$(find /opt/render/.cache/puppeteer -name "chrome" -type f | grep -v "\.initial-preferences" | head -1)
      if [ -n "$CHROME_PATH" ]; then
        echo "Found Chrome at: $CHROME_PATH"
        echo "PUPPETEER_EXECUTABLE_PATH=$CHROME_PATH" >> .env
        chmod +x $CHROME_PATH
      else
        echo "Chrome not found! Attempting direct installation..."
        npx puppeteer browsers install chrome
        CHROME_PATH=$(find /opt/render/.cache/puppeteer -name "chrome" -type f | grep -v "\.initial-preferences" | head -1)
        if [ -n "$CHROME_PATH" ]; then
          echo "Found Chrome at: $CHROME_PATH"
          echo "PUPPETEER_EXECUTABLE_PATH=$CHROME_PATH" >> .env
          chmod +x $CHROME_PATH
        else
          echo "Failed to install Chrome! Deployment may fail."
        fi
      fi
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PUPPETEER_CACHE_DIR
        value: '/opt/render/.cache/puppeteer'
      - key: PUPPETEER_SKIP_DOWNLOAD
        value: 'true'
    healthCheckPath: /health